In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
def percentage_MV(df):
    columns= list(df.columns)
    d = {}
    for x in columns:
        d[x]= df[x].isnull().sum()/len(df[x])
    
    missing_values = pd.DataFrame(d, index=['percentage of missing values'])
    return missing_values.transpose()

In [3]:
data = pd.read_csv(r"/Users/edgartome_1/IronHack/IronProjects/Project5/dataset.csv")
survival = pd.DataFrame(data)
survival

,encounter_id,patient_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,icu_admit_source,...,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,apache_3j_bodysystem,apache_2_bodysystem,Unnamed: 83,hospital_death
0,66154,25312,118,68.0,22.730000,0,Caucasian,M,180.3,Floor,...,1.0,0.0,0.0,0.0,0.0,0.0,Sepsis,Cardiovascular,NaN,0
1,114252,59342,81,77.0,27.420000,0,Caucasian,F,160.0,Floor,...,1.0,0.0,0.0,0.0,0.0,0.0,Respiratory,Respiratory,NaN,0
2,119783,50777,118,25.0,31.950000,0,Caucasian,F,172.7,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic,NaN,0
3,79267,46918,118,81.0,22.640000,1,Caucasian,F,165.1,Operating Room / Recovery,...,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,NaN,0
4,92056,34377,33,19.0,NaN,0,Caucasian,M,188.0,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,Trauma,Trauma,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91708,91592,78108,30,75.0,23.060250,0,Caucasian,M,177.8,Floor,...,1.0,0.0,0.0,0.0,0.0,1.0,Sepsis,Cardiovascular,NaN,0
91709,66119,13486,121,56.0,47.179671,0,Caucasian,F,183.0,Floor,...,0.0,0.0,0.0,0.0,0.0,0.0,Sepsis,Cardiovascular,NaN,0
91710,8981,58179,195,48.0,27.236914,0,Caucasian,M,170.2,Accident & Emergency,...,1.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic,NaN,0
91711,33776,120598,66,NaN,23.297481,0,Caucasian,F,154.9,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,Respiratory,Respiratory,NaN,0
91712,1671,53612,104,82.0,22.031250,1,Caucasian,F,160.0,Operating Room / Recovery,...,0.0,0.0,0.0,0.0,0.0,0.0,Gastrointestinal,Gastrointestinal,NaN,0

In [4]:
survival.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91713 entries, 0 to 91712
Data columns (total 85 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   encounter_id                   91713 non-null  int64
 1   patient_id                     91713 non-null  int64
 2   hospital_id                    91713 non-null  int64
 3   age                            87485 non-null  float64
 4   bmi                            88284 non-null  float64
 5   elective_surgery               91713 non-null  int64
 6   ethnicity                      90318 non-null  object
 7   gender                         91688 non-null  object
 8   height                         90379 non-null  float64
 9   icu_admit_source               91601 non-null  object
 10  icu_id                         91713 non-null  int64
 11  icu_stay_type                  91713 non-null  object
 12  icu_type                       91713 non-null  object
 13  pre_icu_los_days               91713 non-null  float64
 14  weight                         88993 non-null  float64
 15  apache_2_diagnosis             90051 non-null  float64
 16  apache_3j_diagnosis            90612 non-null  float64
 17  apache_post_operative          91713 non-null  int64
 18  arf_apache                     90998 non-null  float64
 19  gcs_eyes_apache                89812 non-null  float64
 20  gcs_motor_apache               89812 non-null  float64
 21  gcs_unable_apache              90676 non-null  float64
 22  gcs_verbal_apache              89812 non-null  float64
 23  heart_rate_apache              90835 non-null  float64
 24  intubated_apache               90998 non-null  float64
 25  map_apache                     90719 non-null  float64
 26  resprate_apache                90479 non-null  float64
 27  temp_apache                    87605 non-null  float64
 28  ventilated_apache              90998 non-null  float64
 29  d1_diasbp_max                  91548 non-null  float64
 30  d1_diasbp_min                  91548 non-null  float64
 31  d1_diasbp_noninvasive_max      90673 non-null  float64
 32  d1_diasbp_noninvasive_min      90673 non-null  float64
 33  d1_heartrate_max               91568 non-null  float64
 34  d1_heartrate_min               91568 non-null  float64
 35  d1_mbp_max                     91493 non-null  float64
 36  d1_mbp_min                     91493 non-null  float64
 37  d1_mbp_noninvasive_max         90234 non-null  float64
 38  d1_mbp_noninvasive_min         90234 non-null  float64
 39  d1_resprate_max                91328 non-null  float64
 40  d1_resprate_min                91328 non-null  float64
 41  d1_spo2_max                    91380 non-null  float64
 42  d1_spo2_min                    91380 non-null  float64
 43  d1_sysbp_max                   91554 non-null  float64
 44  d1_sysbp_min                   91554 non-null  float64
 45  d1_sysbp_noninvasive_max       90686 non-null  float64
 46  d1_sysbp_noninvasive_min       90686 non-null  float64
 47  d1_temp_max                    89389 non-null  float64
 48  d1_temp_min                    89389 non-null  float64
 49  h1_diasbp_max                  88094 non-null  float64
 50  h1_diasbp_min                  88094 non-null  float64
 51  h1_diasbp_noninvasive_max      84363 non-null  float64
 52  h1_diasbp_noninvasive_min      84363 non-null  float64
 53  h1_heartrate_max               88923 non-null  float64
 54  h1_heartrate_min               88923 non-null  float64
 55  h1_mbp_max                     87074 non-null  float64
 56  h1_mbp_min                     87074 non-null  float64
 57  h1_mbp_noninvasive_max         82629 non-null  float64
 58  h1_mbp_noninvasive_min         82629 non-null  float64
 59  h1_resprate_max                87356 non-null  float64
 60  h1_resprate_min                87356 non-null  float64
 61  h1_spo2_max                    87528 non-null  float64
 62  h1_spo2_min                    87528 non-null  float64
 63  h1_sysbp_max                   88102 non-null  float64
 64  h1_sysbp_min                   88102 non-null  float64
 65  h1_sysbp_noninvasive_max       84372 non-null  float64
 66  h1_sysbp_noninvasive_min       84372 non-null  float64
 67  d1_glucose_max                 85906 non-null  float64
 68  d1_glucose_min                 85906 non-null  float64
 69  d1_potassium_max               82128 non-null  float64
 70  d1_potassium_min               82128 non-null  float64
 71  apache_4a_hospital_death_prob  83766 non-null  float64
 72  apache_4a_icu_death_prob       83766 non-null  float64
 73  aids                           90998 non-null  float64
 74  cirrhosis                      90998 non-null  float64
 75  diabetes_mellitus              90998 non-null  float64
 76  hepatic_failure                90998 non-null  float64
 77  immunosuppression              90998 non-null  float64
 78  leukemia                       90998 non-null  float64
 79  lymphoma                       90998 non-null  float64
 80  solid_tumor_with_metastasis    90998 non-null  float64
 81  apache_3j_bodysystem           90051 non-null  object
 82  apache_2_bodysystem            90051 non-null  object
 83  Unnamed: 83                    0 non-null      float64
 84  hospital_death                 91713 non-null  int64
dtypes: float64(71), int64(7), object(7)
memory usage: 59.5+ MB

In [5]:
survival.shape

(91713, 85)

In [6]:
survival.columns

Index(['encounter_id', 'patient_id', 'hospital_id', 'age', 'bmi',
       'elective_surgery', 'ethnicity', 'gender', 'height', 'icu_admit_source',
       'icu_id', 'icu_stay_type', 'icu_type', 'pre_icu_los_days', 'weight',
       'apache_2_diagnosis', 'apache_3j_diagnosis', 'apache_post_operative',
       'arf_apache', 'gcs_eyes_apache', 'gcs_motor_apache',
       'gcs_unable_apache', 'gcs_verbal_apache', 'heart_rate_apache',
       'intubated_apache', 'map_apache', 'resprate_apache', 'temp_apache',
       'ventilated_apache', 'd1_diasbp_max', 'd1_diasbp_min',
       'd1_diasbp_noninvasive_max', 'd1_diasbp_noninvasive_min',
       'd1_heartrate_max', 'd1_heartrate_min', 'd1_mbp_max', 'd1_mbp_min',
       'd1_mbp_noninvasive_max', 'd1_mbp_noninvasive_min', 'd1_resprate_max',
       'd1_resprate_min', 'd1_spo2_max', 'd1_spo2_min', 'd1_sysbp_max',
       'd1_sysbp_min', 'd1_sysbp_noninvasive_max', 'd1_sysbp_noninvasive_min',
       'd1_temp_max', 'd1_temp_min', 'h1_diasbp_max', 'h1_diasbp_min',
       'h1_diasbp_noninvasive_max', 'h1_diasbp_noninvasive_min',
       'h1_heartrate_max', 'h1_heartrate_min', 'h1_mbp_max', 'h1_mbp_min',
       'h1_mbp_noninvasive_max', 'h1_mbp_noninvasive_min', 'h1_resprate_max',
       'h1_resprate_min', 'h1_spo2_max', 'h1_spo2_min', 'h1_sysbp_max',
       'h1_sysbp_min', 'h1_sysbp_noninvasive_max', 'h1_sysbp_noninvasive_min',
       'd1_glucose_max', 'd1_glucose_min', 'd1_potassium_max',
       'd1_potassium_min', 'apache_4a_hospital_death_prob',
       'apache_4a_icu_death_prob', 'aids', 'cirrhosis', 'diabetes_mellitus',
       'hepatic_failure', 'immunosuppression', 'leukemia', 'lymphoma',
       'solid_tumor_with_metastasis', 'apache_3j_bodysystem',
       'apache_2_bodysystem', 'Unnamed: 83', 'hospital_death'],
      dtype='object')

In [7]:
survival.isnull().sum()

encounter_id                       0
patient_id                         0
hospital_id                        0
age                             4228
bmi                             3429
                               ...
solid_tumor_with_metastasis      715
apache_3j_bodysystem            1662
apache_2_bodysystem             1662
Unnamed: 83                    91713
hospital_death                     0
Length: 85, dtype: int64

In [8]:
list_wanted_columns = ['patient_id', 'hospital_id', 'age', 'ethnicity', 'gender', 'height','icu_admit_source','weight','aids','cirrhosis', 'diabetes_mellitus','hepatic_failure', 'immunosuppression', 'leukemia', 'lymphoma','solid_tumor_with_metastasis','hospital_death','d1_heartrate_max', 'd1_heartrate_min','d1_glucose_max', 'd1_glucose_min']
columns = list(survival.columns)
unwanted = [x for x in columns if x not in list_wanted_columns]
for x in unwanted:
    del survival[f'{x}']

In [9]:
survival

,patient_id,hospital_id,age,ethnicity,gender,height,icu_admit_source,weight,d1_heartrate_max,d1_heartrate_min,...,d1_glucose_min,aids,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,hospital_death
0,25312,118,68.0,Caucasian,M,180.3,Floor,73.9,119.0,72.0,...,109.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
1,59342,81,77.0,Caucasian,F,160.0,Floor,70.2,118.0,72.0,...,128.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
2,50777,118,25.0,Caucasian,F,172.7,Accident & Emergency,95.3,96.0,68.0,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,46918,118,81.0,Caucasian,F,165.1,Operating Room / Recovery,61.7,116.0,92.0,...,88.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,34377,33,19.0,Caucasian,M,188.0,Accident & Emergency,NaN,89.0,60.0,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91708,78108,30,75.0,Caucasian,M,177.8,Floor,72.9,115.0,70.0,...,187.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0
91709,13486,121,56.0,Caucasian,F,183.0,Floor,158.0,100.0,76.0,...,177.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
91710,58179,195,48.0,Caucasian,M,170.2,Accident & Emergency,78.9,158.0,79.0,...,86.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
91711,120598,66,NaN,Caucasian,F,154.9,Accident & Emergency,55.9,82.0,60.0,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
91712,53612,104,82.0,Caucasian,F,160.0,Operating Room / Recovery,56.4,104.0,71.0,...,158.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [10]:
survival.isnull().sum()/len(survival)

patient_id                     0.000000
hospital_id                    0.000000
age                            0.046100
ethnicity                      0.015210
gender                         0.000273
height                         0.014545
icu_admit_source               0.001221
weight                         0.029658
d1_heartrate_max               0.001581
d1_heartrate_min               0.001581
d1_glucose_max                 0.063317
d1_glucose_min                 0.063317
aids                           0.007796
cirrhosis                      0.007796
diabetes_mellitus              0.007796
hepatic_failure                0.007796
immunosuppression              0.007796
leukemia                       0.007796
lymphoma                       0.007796
solid_tumor_with_metastasis    0.007796
hospital_death                 0.000000
dtype: float64

In [11]:
#?
columns = list(survival.columns)
for x in survival.columns:
    survival.drop(survival[survival[x].isnull()].index, inplace = True)

In [12]:
survival.isnull().sum()/len(survival)

patient_id                     0.0
hospital_id                    0.0
age                            0.0
ethnicity                      0.0
gender                         0.0
height                         0.0
icu_admit_source               0.0
weight                         0.0
d1_heartrate_max               0.0
d1_heartrate_min               0.0
d1_glucose_max                 0.0
d1_glucose_min                 0.0
aids                           0.0
cirrhosis                      0.0
diabetes_mellitus              0.0
hepatic_failure                0.0
immunosuppression              0.0
leukemia                       0.0
lymphoma                       0.0
solid_tumor_with_metastasis    0.0
hospital_death                 0.0
dtype: float64

In [13]:
list_wanted_columns

['patient_id',
 'hospital_id',
 'age',
 'ethnicity',
 'gender',
 'height',
 'icu_admit_source',
 'weight',
 'aids',
 'cirrhosis',
 'diabetes_mellitus',
 'hepatic_failure',
 'immunosuppression',
 'leukemia',
 'lymphoma',
 'solid_tumor_with_metastasis',
 'hospital_death',
 'd1_heartrate_max',
 'd1_heartrate_min',
 'd1_glucose_max',
 'd1_glucose_min']

# analysis


## Ferdi
height

## Mathieu
age

## Edgar
weight

In [14]:
survival

,patient_id,hospital_id,age,ethnicity,gender,height,icu_admit_source,weight,d1_heartrate_max,d1_heartrate_min,...,d1_glucose_min,aids,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,hospital_death
0,25312,118,68.0,Caucasian,M,180.3,Floor,73.9,119.0,72.0,...,109.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
1,59342,81,77.0,Caucasian,F,160.0,Floor,70.2,118.0,72.0,...,128.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
3,46918,118,81.0,Caucasian,F,165.1,Operating Room / Recovery,61.7,116.0,92.0,...,88.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
5,74489,83,67.0,Caucasian,M,190.5,Accident & Emergency,100.0,113.0,83.0,...,125.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
6,49526,83,59.0,Caucasian,F,165.1,Accident & Emergency,156.6,112.0,70.0,...,129.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91706,59223,121,54.0,Native American,M,177.8,Accident & Emergency,62.5,78.0,55.0,...,91.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
91708,78108,30,75.0,Caucasian,M,177.8,Floor,72.9,115.0,70.0,...,187.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0
91709,13486,121,56.0,Caucasian,F,183.0,Floor,158.0,100.0,76.0,...,177.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
91710,58179,195,48.0,Caucasian,M,170.2,Accident & Emergency,78.9,158.0,79.0,...,86.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
91712,53612,104,82.0,Caucasian,F,160.0,Operating Room / Recovery,56.4,104.0,71.0,...,158.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [ ]:
survival['age'].plot.hist(bins=40)

In [19]:
table1 = pd.crosstab(survival['ethnicity'], survival['hospital_death'])

#table1['% deathe'] = (table1[1]/table[0].sum())*100
table1

hospital_death        0     1
ethnicity
African American   7728   637
Asian               924    81
Caucasian         55480  5101
Hispanic           2930   304
Native American     666    65
Other/Unknown      3647   305

In [23]:
table1['ratio'] = table1[1]/table1[0]
table1

hospital_death        0     1     ratio
ethnicity
African American   7728   637  0.082428
Asian               924    81  0.087662
Caucasian         55480  5101  0.091943
Hispanic           2930   304  0.103754
Native American     666    65  0.097598
Other/Unknown      3647   305  0.083630

In [16]:
# creating pivot table
table2 = pd.pivot_table(survival, index=['ethnicity', 'hospital_death'])

table2

                                       age      aids  cirrhosis  \
ethnicity        hospital_death
African American 0               56.409550  0.003235   0.007893
                 1               63.624804  0.003140   0.020408
Asian            0               61.266234  0.000000   0.015152
                 1               66.925926  0.000000   0.049383
Caucasian        0               63.321179  0.000541   0.014510
                 1               69.189571  0.001372   0.033719
Hispanic         0               61.228669  0.000683   0.026962
                 1               69.687500  0.003289   0.046053
Native American  0               51.025526  0.001502   0.066066
                 1               57.169231  0.000000   0.292308
Other/Unknown    0               57.828626  0.001645   0.024952
                 1               65.183607  0.000000   0.022951

                                 d1_glucose_max  d1_glucose_min  \
ethnicity        hospital_death
African American 0                   178.891563      112.673913
                 1                   194.657771      110.967033
Asian            0                   174.891775      114.862554
                 1                   206.901235      117.506173
Caucasian        0                   171.529903      114.359553
                 1                   198.778475      118.450304
Hispanic         0                   179.023208      113.372355
                 1                   213.506579      120.756579
Native American  0                   183.711712      109.869369
                 1                   198.184615       97.138462
Other/Unknown    0                   182.910886      113.991500
                 1                   206.068852      120.872131

                                 d1_heartrate_max  d1_heartrate_min  \
ethnicity        hospital_death
African American 0                     103.719462         72.721791
                 1                     115.731554         70.675039
Asian            0                     101.954545         71.060606
                 1                     119.925926         69.296296
Caucasian        0                     102.496810         70.179506
                 1                     115.141933         70.438934
Hispanic         0                     102.158703         70.502389
                 1                     114.825658         74.154605
Native American  0                     105.307808         73.444444
                 1                     114.923077         70.600000
Other/Unknown    0                     100.074033         72.585961
                 1                     115.514754         74.540984

                                 diabetes_mellitus      height  \
ethnicity        hospital_death
African American 0                        0.277174  170.837284
                 1                        0.221350  170.786327
Asian            0                        0.278139  162.122749
                 1                        0.185185  164.089383
Caucasian        0                        0.231957  170.285715
                 1                        0.208194  169.497014
Hispanic         0                        0.263140  166.053526
                 1                        0.220395  165.754934
Native American  0                        0.345345  168.540345
                 1                        0.415385  168.042769
Other/Unknown    0                        0.291198  166.688618
                 1                        0.291803  167.047803

                                 hepatic_failure  hospital_id  \
ethnicity        hospital_death
African American 0                      0.007893   101.188535
                 1                      0.012559   106.708006
Asian            0                      0.014069    95.340909
                 1                      0.037037    91.666667
Caucasian        0                      0.012040   107.847873
                 1                      0.029406   106.232307
Hispanic         0                      0.019454    90.458703
                 1                      0.049342    86.240132
Native American  0                      0.057057   110.388889
                 1                      0.230769   108.184615
Other/Unknown    0                      0.014807    98.946257
                 1                      0.026230   109.973770

                                 immunosuppression  leukemia  lymphoma  \
ethnicity        hospital_death
African American 0                        0.021092  0.004788  0.002070
                 1                        0.061224  0.025118  0.004710
Asian            0                        0.023810  0.004329  0.003247
                 1                        0.049383  0.012346  0.024691
Caucasian        0                        0.026118  0.006975  0.004344
                 1                        0.055479  0.015879  0.009410
Hispanic         0                        0.022867  0.005802  0.001706
                 1                        0.016447  0.023026  0.006579
Native American  0                        0.028529  0.004505  0.004505
                 1                        0.015385  0.015385  0.000000
Other/Unknown    0                        0.021113  0.004936  0.003290
                 1                        0.045902  0.006557  0.006557

                                   patient_id  solid_tumor_with_metastasis  \
ethnicity        hospital_death
African American 0               65116.761775                     0.018116
                 1               63923.477237                     0.047096
Asian            0               64740.206710                     0.029221
                 1               64631.469136                     0.061728
Caucasian        0               65519.530425                     0.019701
                 1               66903.902568                     0.048422
Hispanic         0               65524.211604                     0.020137
                 1               61558.401316                     0.029605
Native American  0               65904.210210                     0.010511
                 1               65368.184615                     0.015385
Other/Unknown    0               65467.435975                     0.011242
                 1               64543.449180                     0.036066

                                    weight
ethnicity        hospital_death
African American 0               87.785995
                 1               84.935495
Asian            0               67.367045
                 1               65.573210
Caucasian        0               85.501336
                 1               82.631268
Hispanic         0               79.368778
                 1               75.738388
Native American  0               88.254174
                 1               86.849231
Other/Unknown    0               79.870211
                 1               80.037410

In [24]:
table3 = pd.crosstab(survival['gender'], survival['hospital_death'])
table3

hospital_death      0     1
gender
F               32297  2984
M               39078  3509

In [25]:
table3['ratio'] = table3[1]/table3[0]
table3

hospital_death      0     1     ratio
gender
F               32297  2984  0.092392
M               39078  3509  0.089795

In [26]:
survival.describe()

,patient_id,hospital_id,age,height,weight,d1_heartrate_max,d1_heartrate_min,d1_glucose_max,d1_glucose_min,aids,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,hospital_death
count,77868.000000,77868.000000,77868.000000,77868.000000,77868.000000,77868.000000,77868.000000,77868.000000,77868.000000,77868.000000,77868.000000,77868.000000,77868.000000,77868.000000,77868.000000,77868.000000,77868.000000,77868.000000
mean,65528.630066,105.781322,62.587379,169.814684,84.770181,103.573817,70.648135,175.551998,114.385049,0.000950,0.016990,0.240561,0.013998,0.027521,0.007371,0.004328,0.021447,0.083385
std,37748.567522,63.695251,16.589813,10.740621,25.102918,21.946879,16.938734,87.281422,38.320421,0.030813,0.129236,0.427427,0.117483,0.163597,0.085541,0.065644,0.144868,0.276465
min,1.000000,2.000000,16.000000,137.200000,38.600000,58.000000,0.000000,73.000000,33.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,32951.250000,47.000000,53.000000,162.600000,67.600000,88.000000,60.000000,118.000000,90.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,65330.500000,112.000000,65.000000,170.100000,81.200000,101.000000,70.000000,151.000000,107.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,98238.250000,166.000000,75.000000,177.800000,97.900000,117.000000,81.000000,202.000000,131.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,131051.000000,204.000000,89.000000,195.590000,186.000000,177.000000,160.000000,611.000000,288.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [27]:
survival.corr()

,patient_id,hospital_id,age,height,weight,d1_heartrate_max,d1_heartrate_min,d1_glucose_max,d1_glucose_min,aids,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,hospital_death
patient_id,1.000000,-0.004589,0.003576,0.005050,0.000817,0.002802,0.004020,-0.003782,0.002021,-0.001734,0.003256,-0.000275,-0.002329,0.001823,0.000415,0.003898,-0.003090,0.005417
hospital_id,-0.004589,1.000000,-0.006226,0.030038,0.026118,-0.010262,-0.005258,-0.002270,0.018863,-0.005319,0.003207,0.012996,0.002575,-0.000866,-0.003855,0.002336,-0.007316,-0.002011
age,0.003576,-0.006226,1.000000,-0.113113,-0.126556,-0.146805,-0.150140,0.010718,0.064858,-0.030260,-0.030885,0.069833,-0.022662,0.022459,0.028478,0.022902,0.024415,0.104409
height,0.005050,0.030038,-0.113113,1.000000,0.382380,-0.016707,-0.029269,-0.013800,0.017165,0.009913,0.010292,-0.004039,0.007314,-0.001761,0.002417,0.010343,0.002963,-0.015823
weight,0.000817,0.026118,-0.126556,0.382380,1.000000,-0.040591,-0.001613,0.085640,0.136921,-0.018304,-0.002051,0.158940,0.000032,-0.034716,-0.013324,-0.004980,-0.042810,-0.030374
d1_heartrate_max,0.002802,-0.010262,-0.146805,-0.016707,-0.040591,1.000000,0.474521,0.110061,0.052762,0.009923,0.013225,-0.031553,0.016170,0.063490,0.023461,0.019973,0.044774,0.160602
d1_heartrate_min,0.004020,-0.005258,-0.150140,-0.029269,-0.001613,0.474521,1.000000,0.099741,0.057716,0.013411,0.019985,0.017293,0.021184,0.049834,0.011043,0.012954,0.040861,0.002991
d1_glucose_max,-0.003782,-0.002270,0.010718,-0.013800,0.085640,0.110061,0.099741,1.000000,0.382744,-0.011942,-0.004936,0.413770,-0.009527,-0.007510,-0.005535,-0.002941,-0.015362,0.082762
d1_glucose_min,0.002021,0.018863,0.064858,0.017165,0.136921,0.052762,0.057716,0.382744,1.000000,-0.008271,-0.016515,0.141764,-0.018330,0.004257,-0.005042,0.000267,0.011557,0.026192
aids,-0.001734,-0.005319,-0.030260,0.009913,-0.018304,0.009923,0.013411,-0.011942,-0.008271,1.000000,0.008845,-0.011508,0.003420,0.025383,-0.002658,0.017014,-0.001689,0.005773
cirrhosis,0.003256,0.003207,-0.030885,0.010292,-0.002051,0.013225,0.019985,-0.004936,-0.016515,0.008845,1.000000,0.010634,0.535824,-0.004501,-0.005521,0.000415,-0.005744,0.042659
diabetes_mellitus,-0.000275,0.012996,0.069833,-0.004039,0.158940,-0.031553,0.017293,0.413770,0.141764,-0.011508,0.010634,1.000000,0.007107,-0.005055,0.003132,-0.003693,-0.015293,-0.017493
hepatic_failure,-0.002329,0.002575,-0.022662,0.007314,0.000032,0.016170,0.021184,-0.009527,-0.018330,0.003420,0.535824,0.007107,1.000000,0.003342,-0.001322,0.000471,0.007261,0.042746
immunosuppression,0.001823,-0.000866,0.022459,-0.001761,-0.034716,0.063490,0.049834,-0.007510,0.004257,0.025383,-0.004501,-0.005055,0.003342,1.000000,0.142429,0.103710,0.271501,0.047506
leukemia,0.000415,-0.003855,0.028478,0.002417,-0.013324,0.023461,0.011043,-0.005535,-0.005042,-0.002658,-0.005521,0.003132,-0.001322,0.142429,1.000000,0.030911,0.005896,0.032657
lymphoma,0.003898,0.002336,0.022902,0.010343,-0.004980,0.019973,0.012954,-0.002941,0.000267,0.017014,0.000415,-0.003693,0.000471,0.103710,0.030911,1.000000,0.014548,0.020450
solid_tumor_with_metastasis,-0.003090,-0.007316,0.024415,0.002963,-0.042810,0.044774,0.040861,-0.015362,0.011557,-0.001689,-0.005744,-0.015293,0.007261,0.271501,0.005896,0.014548,1.000000,0.052506
hospital_death,0.005417,-0.002011,0.104409,-0.015823,-0.030374,0.160602,0.002991,0.082762,0.026192,0.005773,0.042659,-0.017493,0.042746,0.047506,0.032657,0.020450,0.052506,1.000000

In [35]:
from scipy.stats import ttest_ind


r1 = ttest_ind(survival['d1_heartrate_max'], survival['d1_heartrate_min'], equal_var=False).pvalue

r1

0.0

In [36]:
def lazy2(i):
        if i < 0.05:
             print(':hypothesis is rejected: the difference is significant')
        elif i >= 0.05 and i<=0.1:
             print(':hypothesis rejected: but not highly confident')
        else:
             print(':hypothesis not rejected')
lazy2(r1)

:hypothesis is rejected: the difference is significant

In [ ]:


from scipy.stats import ttest_rel


r1 = ttest_rel(survival['d1_heartrate_max'], survival.['Total'], equal_var=False).pvalue


def lazy2(i):
        if i < 0.05:
             print(':hypothesis is rejected: the difference is significant')
        elif i >= 0.05 and i<=0.1:
             print(':hypothesis rejected: but not highly confident')
        else:
             print(':hypothesis not rejected')
lazy2(r1)
print(r1)

In [ ]:
#def chart1(x):
 
# creating pivot table
#table = pd.pivot_table(survival, index=['Gender', 'Name'])
  
# calculating percentage
#table['% Income'] = (table['Salary(in $)']/table['Salary(in $)'].sum())*100
  
# display table
#print("Pivot Table")
#print(table)